#!/usr/bin/env bash
set -e

# move VS code data directory into capsule, so it persists
ln -s /root/capsule/.vscode/ /.vscode

# install updated version of code-server
VERSION=4.93.1
mkdir /.code-server
cd /.code-server
curl -fL "https://github.com/coder/code-server/releases/download/v$VERSION/code-server-$VERSION-linux-amd64.tar.gz" \
  | tar -xvz
ln -s /.code-server/code-server-$VERSION-linux-amd64/bin/code-server  /usr/bin/code-server
cd -

pip install git+https://github.com/AllenNeuralDynamics/aind-data-schema.git@dev